# Generated by Django 5.2 on 2025-05-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nit", models.CharField(max_length=20, unique=True, verbose_name="NIT")),
                ("name", models.CharField(max_length=255, verbose_name="Nombre de la empresa")),
                ("address", models.CharField(max_length=255, verbose_name="Dirección")),
                ("phone", models.CharField(max_length=20, verbose_name="Teléfono")),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
    ]
