from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from io import BytesIO
from django.core.mail import EmailMessage
from django.conf import settings
import tempfile
from datetime import datetime
import logging

from apps.inventories.models import Inventory

logger = logging.getLogger(__name__)


def create_inventory_pdf(buffer: BytesIO, inventory_items: list[Inventory], title: str = "Inventory Report", company_name: str = None) -> BytesIO:
    """
    Common function to create an elegant PDF with inventory information.
    
    Args:
        buffer: BytesIO buffer to write the PDF to
        inventory_items: Queryset or list of inventory items
        title: Title for the PDF
        company_name: Optional company name for customization
    
    Returns:
        The buffer with the PDF content
    """
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Create elements for the PDF
    elements = []
    
    # Title
    title_style = styles["Heading1"]
    title_style.alignment = 1  # Centered
    elements.append(Paragraph(title, title_style))
    elements.append(Spacer(1, 20))
    
    # Date
    date_style = styles["Normal"]
    date_style.alignment = 1  # Centered
    elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", date_style))
    elements.append(Spacer(1, 30))
    
    # Resumen
    elements.append(Paragraph(f"Total products in inventory: {len(inventory_items)}", styles["Normal"]))
    elements.append(Spacer(1, 20))
    
    # Data for the table
    if company_name:
        # For a specific company, no need to include company column
        data = [["ID", "Product", "Code", "Quantity", "Date"]]
        
        for item in inventory_items:
            data.append([
                str(item.id),
                item.product.name,
                item.product.code,
                str(item.quantity),
                item.created_at.strftime("%d/%m/%Y %H:%M")
            ])
    else:
        # For all companies, include company column
        data = [["ID", "Company", "Product", "Code", "Quantity", "Date"]]
        
        for item in inventory_items:
            data.append([
                str(item.id),
                item.company.name,
                item.product.name,
                item.product.code,
                str(item.quantity),
                item.created_at.strftime("%d/%m/%Y %H:%M")
            ])
    
    # Create the table
    table = Table(data, repeatRows=1)
    
    # Table style
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ('TOPPADDING', (0, 1), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
    ]))
    
    elements.append(table)
    elements.append(Spacer(1, 30))
    
    # Footer
    footer_style = styles["Normal"]
    footer_style.alignment = 1  # Centered
    footer_style.fontSize = 8
    elements.append(Paragraph("This document was automatically generated by the inventory system.", footer_style))
    
    if company_name:
        elements.append(Paragraph(f"© {datetime.now().year} {company_name} - All rights reserved", footer_style))
    else:
        elements.append(Paragraph(f"© {datetime.now().year} Lite Thinking - All rights reserved", footer_style))
    
    # Generate the PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer


def generate_inventory_pdf_for_email(inventory_data: list[Inventory], company_name: str = None) -> str:
    """
    Generate an elegant PDF with the inventory information using ReportLab.
    Returns the path to a temporary file with the PDF.
    """
    buffer = BytesIO()
    create_inventory_pdf(
        buffer=buffer, 
        inventory_items=inventory_data, 
        title=f"Inventory of {company_name}", 
        company_name=company_name
    )
    
    # Create a temporary file
    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as temp_file:
        temp_file.write(buffer.getvalue())
        return temp_file.name


def send_inventory_email(email: str, pdf_path: str, company_name: str = None) -> None:
    """
    Envía el PDF del inventario por correo electrónico.
    """
    subject = f'Inventory of {company_name}' if company_name else 'Inventory of all companies'
    message = f'Please find attached the inventory of {company_name}.' if company_name else 'Please find attached the inventory of all companies.'
    
    logger.info(f"Sending email to {email} with subject {subject} and message {message}")
    
    # Create the HTML body of the email
    html_message = f"""
    <html>
    <body>
        <h2>Inventory Report</h2>
        <p>Dear user,</p>
        <p>{message}</p>
        <p>This is an automated message, please do not reply.</p>
        <hr>
        <p style="font-size: small; color: gray;">© {datetime.now().year} - Lite Thinking Inventory System</p>
    </body>
    </html>
    """
    
    # Create the EmailMessage object
    email_message = EmailMessage(
        subject=subject,
        body=html_message,
        from_email=settings.DEFAULT_FROM_EMAIL,
        to=[email]
    )
    
    # Set the content as HTML
    email_message.content_subtype = "html"
    
    # Attach the PDF
    with open(pdf_path, 'rb') as f:
        email_message.attach('inventory.pdf', f.read(), 'application/pdf')
    
    # Send the email
    email_message.send(fail_silently=False)
    
    logger.info(f"Email sent successfully to {email}")


def generate_inventory_pdf(inventory_queryset: list[Inventory]) -> BytesIO:
    """
    Generate inventory PDF using ReportLab for download
    Uses the common function to create the PDF
    """
    buffer = BytesIO()
    return create_inventory_pdf(buffer, inventory_queryset)
